# must be unique in a given SonarQube instance
sonar.projectKey=chef_knife_b931915d-6570-49f6-944c-d476320c7c10

sonar.projectName=knife

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# skip C-language processor
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-